FRAC = 0.1

DIN_SESS_MAX_LEN = 50

DSIN_SESS_COUNT = 5
DSIN_SESS_MAX_LEN = 10
FEAD_DICT = ["userid","adgroup_id","pid","cms_segid","cms_group_id","final_gender_code","age_level",'pvalue_level','shopping_level','occupation',
             'new_user_class_level','campaign_id','customer','cate_id','brand',]
# 1111 ListWrapper([SparseFeat(name='userid', vocabulary_size=106177, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D88611C50>, embedding_name='userid', group_name='default_group', trainable=True),
# SparseFeat(name='adgroup_id', vocabulary_size=355946, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D88611DA0>, embedding_name='adgroup_id', group_name='default_group', trainable=True),
# SparseFeat(name='pid', vocabulary_size=2, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D88611E48>, embedding_name='pid', group_name='default_group', trainable=True),
# SparseFeat(name='cms_segid', vocabulary_size=97, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D88611E80>, embedding_name='cms_segid', group_name='default_group', trainable=True),
# SparseFeat(name='cms_group_id', vocabulary_size=13, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D88611EB8>, embedding_name='cms_group_id', group_name='default_group', trainable=True),
# SparseFeat(name='final_gender_code', vocabulary_size=2, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D88611EF0>, embedding_name='final_gender_code', group_name='default_group', trainable=True),
# SparseFeat(name='age_level', vocabulary_size=7, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D88611F28>, embedding_name='age_level', group_name='default_group', trainable=True),
# SparseFeat(name='pvalue_level', vocabulary_size=4, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D88611F60>, embedding_name='pvalue_level', group_name='default_group', trainable=True),
# SparseFeat(name='shopping_level', vocabulary_size=3, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D88611F98>, embedding_name='shopping_level', group_name='default_group', trainable=True),
# SparseFeat(name='occupation', vocabulary_size=2, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D88611FD0>, embedding_name='occupation', group_name='default_group', trainable=True),
# SparseFeat(name='new_user_class_level', vocabulary_size=5, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D8862D048>, embedding_name='new_user_class_level', group_name='default_group', trainable=True),
# SparseFeat(name='campaign_id', vocabulary_size=236155, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D8862D080>, embedding_name='campaign_id', group_name='default_group', trainable=True),
# SparseFeat(name='customer', vocabulary_size=155112, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D8862D0B8>, embedding_name='customer', group_name='default_group', trainable=True),
# Spars'brand', vocabulary_size=101188, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D8862D198>, embedding_name='brand', group_name='default_group', trainable=True)])eFeat(name='cate_id', vocabulary_size=6961, embedding_dim=4, use_hash=False, vocabulary_path=None, dtype='int32', embeddings_initializer=<tensorflow.python.keras.initializers.RandomNormal object at 0x0000025D8862D128>, embedding_name='cate_id', group_name='default_group', trainable=True),
# SparseFeat(name=


#embedding_dict {'userid': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB54FE48>, 'adgroup_id': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB5790B8>, 'pid': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB5792E8>, 'cms_segid': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB579518>, 'cms_group_id': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB579748>, 'final_gender_code': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB579978>, 'age_level': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB579BA8>, 'pvalue_level': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB579DD8>, 'shopping_level': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB57F048>, 'occupation': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB57F278>, 'new_user_class_level': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB57F4A8>, 'campaign_id': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB57F6D8>, 'customer': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB57F908>, 'cate_id': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB57FB38>, 'brand': <tensorflow.python.keras.layers.embeddings.Embedding object at 0x000001FDAB57FD68>}
